filter_node:
  ros__parameters:
    use_sim_time: False
    odom_topic: "odom_delta"
    odom_covariance: [
      0.1,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.1,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.05, 0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  1.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  1.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.5
    ]
    imu_topic: "imu"
    imu_covariance: [
      2.5655e-06, -2.43442e-07, 4.32885e-07, 
      -2.43442e-07, 4.20833e-05, -2.11885e-05, 
      4.32885e-07, -2.11885e-05, 6.69333e-05
    ]
    process_noise: [
      1e-1, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  1e-1, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  1e-1, 0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  1e-1, 0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  1e-1, 0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  1e-1, 0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-1, 0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-1
    ]
microcontroller_interface:
  ros__parameters:
    odom_port: "/dev/ttyACM0"
    imu_port: "/dev/ttyUSB0"
keyboard_teleop:
  ros__parameters:
    vx: 0.1
    vy: 0.1
    vtheta: 0.6
    cmd_vel_topic: "cmd_vel" 
